/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as V1SplatRouteImport } from './routes/v1/$'
import { Route as V1MessagesRouteImport } from './routes/v1/messages'
import { Route as V1ModelsRouteImport } from './routes/v1/models'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as AuthenticatedAccountApiKeysRouteImport } from './routes/_authenticated/account.api-keys'
import { Route as AuthenticatedAccountLiveConsoleRouteImport } from './routes/_authenticated/account.live-console'
import { Route as AuthenticatedAccountSecurityRouteImport } from './routes/_authenticated/account.security'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as ApiLiveConsoleEventsRouteImport } from './routes/api/live-console/events'
import { Route as V1ChatCompletionsRouteImport } from './routes/v1/chat/completions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const V1SplatRoute = V1SplatRouteImport.update({
  id: '/v1/$',
  path: '/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MessagesRoute = V1MessagesRouteImport.update({
  id: '/v1/messages',
  path: '/v1/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ModelsRoute = V1ModelsRouteImport.update({
  id: '/v1/models',
  path: '/v1/models',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountApiKeysRoute =
  AuthenticatedAccountApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountLiveConsoleRoute =
  AuthenticatedAccountLiveConsoleRouteImport.update({
    id: '/live-console',
    path: '/live-console',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountSecurityRoute =
  AuthenticatedAccountSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiLiveConsoleEventsRoute = ApiLiveConsoleEventsRouteImport.update({
  id: '/api/live-console/events',
  path: '/api/live-console/events',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ChatCompletionsRoute = V1ChatCompletionsRouteImport.update({
  id: '/v1/chat/completions',
  path: '/v1/chat/completions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/v1/$': typeof V1SplatRoute
  '/v1/messages': typeof V1MessagesRoute
  '/v1/models': typeof V1ModelsRoute
  '/account/api-keys': typeof AuthenticatedAccountApiKeysRoute
  '/account/live-console': typeof AuthenticatedAccountLiveConsoleRoute
  '/account/security': typeof AuthenticatedAccountSecurityRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/live-console/events': typeof ApiLiveConsoleEventsRoute
  '/v1/chat/completions': typeof V1ChatCompletionsRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/v1/$': typeof V1SplatRoute
  '/v1/messages': typeof V1MessagesRoute
  '/v1/models': typeof V1ModelsRoute
  '/account/api-keys': typeof AuthenticatedAccountApiKeysRoute
  '/account/live-console': typeof AuthenticatedAccountLiveConsoleRoute
  '/account/security': typeof AuthenticatedAccountSecurityRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/live-console/events': typeof ApiLiveConsoleEventsRoute
  '/v1/chat/completions': typeof V1ChatCompletionsRoute
  '/account': typeof AuthenticatedAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/v1/$': typeof V1SplatRoute
  '/v1/messages': typeof V1MessagesRoute
  '/v1/models': typeof V1ModelsRoute
  '/_authenticated/account/api-keys': typeof AuthenticatedAccountApiKeysRoute
  '/_authenticated/account/live-console': typeof AuthenticatedAccountLiveConsoleRoute
  '/_authenticated/account/security': typeof AuthenticatedAccountSecurityRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/live-console/events': typeof ApiLiveConsoleEventsRoute
  '/v1/chat/completions': typeof V1ChatCompletionsRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/setup'
    | '/account'
    | '/v1/$'
    | '/v1/messages'
    | '/v1/models'
    | '/account/api-keys'
    | '/account/live-console'
    | '/account/security'
    | '/admin/users'
    | '/api/live-console/events'
    | '/v1/chat/completions'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/setup'
    | '/v1/$'
    | '/v1/messages'
    | '/v1/models'
    | '/account/api-keys'
    | '/account/live-console'
    | '/account/security'
    | '/admin/users'
    | '/api/live-console/events'
    | '/v1/chat/completions'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/setup'
    | '/_authenticated/account'
    | '/v1/$'
    | '/v1/messages'
    | '/v1/models'
    | '/_authenticated/account/api-keys'
    | '/_authenticated/account/live-console'
    | '/_authenticated/account/security'
    | '/_authenticated/admin/users'
    | '/api/live-console/events'
    | '/v1/chat/completions'
    | '/_authenticated/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SetupRoute: typeof SetupRoute
  V1SplatRoute: typeof V1SplatRoute
  V1MessagesRoute: typeof V1MessagesRoute
  V1ModelsRoute: typeof V1ModelsRoute
  ApiLiveConsoleEventsRoute: typeof ApiLiveConsoleEventsRoute
  V1ChatCompletionsRoute: typeof V1ChatCompletionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/v1/$': {
      id: '/v1/$'
      path: '/v1/$'
      fullPath: '/v1/$'
      preLoaderRoute: typeof V1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/messages': {
      id: '/v1/messages'
      path: '/v1/messages'
      fullPath: '/v1/messages'
      preLoaderRoute: typeof V1MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/models': {
      id: '/v1/models'
      path: '/v1/models'
      fullPath: '/v1/models'
      preLoaderRoute: typeof V1ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/api-keys': {
      id: '/_authenticated/account/api-keys'
      path: '/api-keys'
      fullPath: '/account/api-keys'
      preLoaderRoute: typeof AuthenticatedAccountApiKeysRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/live-console': {
      id: '/_authenticated/account/live-console'
      path: '/live-console'
      fullPath: '/account/live-console'
      preLoaderRoute: typeof AuthenticatedAccountLiveConsoleRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/security': {
      id: '/_authenticated/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AuthenticatedAccountSecurityRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/live-console/events': {
      id: '/api/live-console/events'
      path: '/api/live-console/events'
      fullPath: '/api/live-console/events'
      preLoaderRoute: typeof ApiLiveConsoleEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/chat/completions': {
      id: '/v1/chat/completions'
      path: '/v1/chat/completions'
      fullPath: '/v1/chat/completions'
      preLoaderRoute: typeof V1ChatCompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountApiKeysRoute: typeof AuthenticatedAccountApiKeysRoute
  AuthenticatedAccountLiveConsoleRoute: typeof AuthenticatedAccountLiveConsoleRoute
  AuthenticatedAccountSecurityRoute: typeof AuthenticatedAccountSecurityRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountApiKeysRoute: AuthenticatedAccountApiKeysRoute,
  AuthenticatedAccountLiveConsoleRoute: AuthenticatedAccountLiveConsoleRoute,
  AuthenticatedAccountSecurityRoute: AuthenticatedAccountSecurityRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SetupRoute: SetupRoute,
  V1SplatRoute: V1SplatRoute,
  V1MessagesRoute: V1MessagesRoute,
  V1ModelsRoute: V1ModelsRoute,
  ApiLiveConsoleEventsRoute: ApiLiveConsoleEventsRoute,
  V1ChatCompletionsRoute: V1ChatCompletionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
